feat: add payments API
vipago/mpago pull request #2
Opened 2023-09-06 16:24 UTC by D4v3sb

Closes #1

2023-09-10 03:49 UTC, coffee-is-power commented
Ae vou dar uma olhada

2023-09-10 04:46 UTC, coffee-is-power requested changes
Tá bom no geral, mas tem umas coisinhas pra melhorar.

2023-09-10 04:46 UTC, coffee-is-power commented on src/oauth.rs
>  impl OAuth {
Acho que talvez era melhor tirar essa struct aqui, deixa as funções direto no módulo, porque tipo todas as funções desta struct são estaticas e também n e suporto você instanciar está struct, então ser uma struct não faz muito sentido não.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments.rs
> +    transaction_amount: f32,
Isto é ok, mas se for precisar de somar preços ou fazer qualquer conta com os preços, nao se esqueci de levar moedas em conta e usar Decimal invés de float.

Lembra te que a vipago guarda tudo em Decimal no banco de dados e sempre trabalha com decimals.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments.rs
> +}
Esta função e meio inútil, e melhor a pessoa criar a struct direto já que o `PaymentSearchBuilder` e só um wrapper em volta das options.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payer.rs
> +    pub entity_type: Option<EntityType>,
Dá pra ser um pouco mais claro no que isto é? eu não entendi n...

2023-09-10 04:46 UTC, coffee-is-power commented on src/payer.rs
> +    Registered,
Essa variante n tá documentada

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments.rs
> +}
Outra função que e melhor o usuário criar a struct direto

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments.rs
> +}
Mais uma

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/search_builder.rs
> +    /// Send the request
Essa documentação ta errada


```suggestion
    /// This function creates a stream of payments, it goes through all the pages.
    /// When you fetch a payment, it will check if you reached the end of a page, if you have, it will fetch another page and returno the first payment on that page, other wise it gives you the next payment from the current page
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/search_builder.rs
> +    pub async fn send<'a>(
E também renomeia essa função para `fetch_all_streamed`

```suggestion
    pub async fn fetch_all_streamed<'a>(
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +    /// It is related to `begin_date` and `end_date`
Esta descrição e absolutamente horrível


```suggestion
    /// Defines which date field Mercado Pago should check when searching using `begin_date` and `end_date`
    /// 
    /// What this means is that you can filter by update, created date or whatever date
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +    /// Pagination information for search results.
Por favor evita repetir a mesma documentação que está dentro do tipo nas fields que usam esse tipo.

```suggestion
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +/// Struct to use in [`PaymentCreateBuilder`](crate::payments::PaymentCreateBuilder)
```suggestion
/// Used as the request body for creating payments
///
///  See [`PaymentCreateBuilder`](crate::payments::PaymentCreateBuilder) if you want to create payments.
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +    pub description: String,
Description deveria ser um `Option<String>`

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +}
Só uma sugestão, talvez não seria má ideia adicionar utilidades pra conseguir descodificar o QRcode. Não e absolutamente essencial mas pode ser útil.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +}
Só uma sugestão, talvez não seria má ideia adicionar utilidades pra conseguir descodificar o QRcode. Não e absolutamente essencial mas pode ser útil.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +    /// The merchant will use the Mercado Pago merchant codes and will take advantage of the financial advantages that we offer.
```suggestion
    /// The merchant will use the Mercado Pago merchant codes and will take advantage of the financial advantages that Mercado Pago offers.
```

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +}
Adiciona uma função pra converter `iso_currency` nesse e um aí, ou só usar o `iso_currency` direto. Vai ser chato converter dentro da vipago entre os dois. Não e nada divertido acredita.

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/types.rs
> +    #[serde(rename = "bolbradesco")]
Isso tá certo? Não era ticket?

2023-09-10 04:46 UTC, coffee-is-power commented on src/payments/update_builder.rs
> +pub struct PaymentUpdateBuilder(pub u64, pub PaymentUpdateOptions);
Acho que aqui podias considerar usar uma struct normal invés de tupla, structs de tupla são usados em situações que o propósito dos valores são possíveis de identificar pelo tipo do valor, mas aqui você já precisou documentar entao aq ta usando no lugar errado

```suggestion
pub struct PaymentUpdateBuilder {
    pub id: u64, 
    pub options: PaymentUpdateOptions
}
```

2023-09-10 04:48 UTC, coffee-is-power commented
Dei review quase as 6 da manhã krl aq um gajo n dorme e tipo Deus, só espero que não tenha lagado :joy:

2023-09-10 14:13 UTC, D4v3sb commented on src/payments/types.rs
> +    #[serde(rename = "bolbradesco")]
Está certo. O ticket é do [`PaymentTypeId`](https://github.com/vipago/mpago/pull/2/files/9dcb96359dbc3f8f5de08cbb83221d4053d5a4bf#diff-60abaa19fa15c2c3ce50f70e7c3f9e3183c2464f687574fa7645f2975e9e27adR518), que é um parâmetro de resposta.

2023-09-10 14:19 UTC, D4v3sb commented on src/payments.rs
> +    transaction_amount: f32,
Utilizar a crate [`rust_decimal`](https://docs.rs/rust_decimal/latest/rust_decimal/) ou outra abordagem?

2023-09-10 14:23 UTC, D4v3sb commented on src/payer.rs
> +    pub entity_type: Option<EntityType>,
É toda informação que o Mercado Pago disponibiliza sobre. 

É somente para transações bancárias, é a entidade da conta do banco, que pode ser individual ou uma associação, voltada para empresas/instituições.

2023-09-10 14:24 UTC, coffee-is-power commented on src/payments.rs
> +    transaction_amount: f32,
O Decimal é preciso uma crate chamada `rust_decimal`. Ele representa numeros com o nnumero inteiro e o numero de casas decimais, por exemplo:

- 10,60 -> é representado como 1060 2
- 6,7555 -> é representado como 67555 4

Como não é baseado em aproximações, expoentes ou mantissas, ele vai ser muito mais preciso do que floats normais.

2023-09-10 15:32 UTC, coffee-is-power commented on src/payments/types.rs
> +    #[serde(rename = "bolbradesco")]
A beleza então

2023-09-12 00:23 UTC, coffee-is-power commented on src/payer.rs
> +    Registered,
```suggestion
```

2023-09-13 21:35 UTC, coffee-is-power commented on src/payments/types.rs
> +}
Na verdade isto não é preciso fazer no backend, so o frontend vai precisar de sequer saber como lidar com isto, então eu vou resolver esta conversa

2023-09-13 22:34 UTC, coffee-is-power commented on src/payments/update_builder.rs
> +pub struct PaymentUpdateBuilder(pub u64, pub PaymentUpdateOptions);
Arrumado no commit [e34dfc0](https://github.com/vipago/mpago/pull/2/commits/e34dfc07e093bcc0380c23347dcb820f5a3babc5)

2023-09-13 22:35 UTC, coffee-is-power commented on src/payments/search_builder.rs
> +    pub async fn send<'a>(
Arrumado no commit [e28f3b1](https://github.com/vipago/mpago/pull/2/commits/e28f3b1ac668dc1aa5a7d7953cc4cc90047f51be)

2023-09-13 22:35 UTC, coffee-is-power commented on src/payments/types.rs
> +    pub description: String,
Arrumado no commit 77bbaffea1bdd6cb580280bdb0a27882ea1597ad

2023-09-13 22:38 UTC, coffee-is-power commented on src/payments/types.rs
> +}
```suggestion
#[derive(Deserialize_enum_str, Serialize_enum_str, Debug, PartialEq, Eq)]
pub enum CurrencyId {
    ARS,
    BRL,
    CLP,
    MXN,
    COP,
    PEN,
    UYU,
    VES,
    MCN,
    BTC,
    USD,
    USDP,
    DCE,
    ETH,
    FDI,
    CDB,
    #[serde(other)]
    Unknown(String),
}
impl TryFrom<Currency> for CurrencyId {
    type Error = ();
    fn try_from(value: Currency) -> Result<Self, Self::Error> {
        match value {
            Currency::{...} => Self::{...},
            // ....
        }
    }
}
```

2023-09-17 10:43 UTC, coffee-is-power approved these changes
Agora eu gostei :+1: 
Ta pronto pra dar merge!

2023-09-17 10:43 UTC, merged