feat: add wallet connect API support
vipago/mpago pull request #9
Opened 2023-10-03 12:33 UTC by coffee-is-power

Esse pull request adiciona suporte a api de **wallet connect** do mercafo pago, que permite a conexão da carteira do cliente com a aplicação para pagamentos futuros.

Closes #7

2023-10-03 12:50 UTC, D4v3sb requested changes
Falta agora a parte de criar o Payer Token

2023-10-03 12:50 UTC, D4v3sb commented on src/client.rs
> +    #[must_use]
Pra que esse `#[must_use]`. Não entendi muito bem como ele funciona.

2023-10-03 12:53 UTC, coffee-is-power commented on src/client.rs
> +    #[must_use]
Ele serve pra obrigar o usuário da função a usar o valor de retorno. Você pode colocar em funções ou em tipos como structs ou enums.

2023-10-03 12:56 UTC, D4v3sb commented on src/client.rs
> +    #[must_use]
Ah, entendi

2023-10-03 13:22 UTC, coffee-is-power commented
Acabei de adicionar uma função pra criar o builder dos agreements porque eu tinha esquecido

2023-10-13 23:10 UTC, D4v3sb commented
Fechar PR pelo mesmo motivo da issue

https://github.com/vipago/mpago/issues/7#issuecomment-1757974905

2023-10-21 17:20 UTC, closed without merging